config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: redirect("/books")

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",

    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :follows, only: [:create, :destroy]
  resources :followings, only: [:show]
  resources :followers, only: [:show]
  resources :users

  resources :books do
    resources :comments
  end

  resources :reports do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  paginates_per 5
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_commentable
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @commentable.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @commentable, notice: I18n.t(:Model_was_successfully_created, model: Comment.model_name.human) }
        format.json { render :show, status: :created, location: @commentable }
      else
        format.html { render :new }
        format.json { render json: @commentable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to [@commentable, @comment], notice: I18n.t(:Model_was_successfully_updated, model: Comment.model_name.human) }
        format.json { render :show, status: :ok, location: [@commentable, @comment] }
      else
        format.html { render :edit }
        format.json { render json: [@commentable, @comment].errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @commentable, notice: I18n.t(:Model_was_successfully_destroyed, model: Comment.model_name.human) }
      format.json { head :no_content }
    end
  end

  private
    def set_commentable
      resource, id = request.path.split("/")[1, 2]
      @commentable = resource.singularize.classify.constantize.find(id)
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:commentable, :name, :memo)
    end
end

app/views/comments/_form.html.slim
= form_with(model: [@commentable, comment], local: true) do |form|
  - if comment.errors.any?
    #error_explanation
      h2
        = pluralize(comment.errors.count, t(:error))
        = t(:prohibited_this_model_from_being_saved, model: Comment.model_name.human)
      ul
        - comment.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :memo
    = form.text_area :memo
  .actions
    = form.submit

app/views/comments/edit.html.slim
h1
  = t(:Editing_Model, model: @comment.model_name.human)
= render "form", comment: @comment
= link_to t(:Back), @commentable

app/views/comments/index.html.slim
h3
  = "#{Comment.model_name.human}: "
- @comments = commentable.comments.page(params[:page])
- if commentable.comments.any?
  ul
    - @comments.each do |comment|
      li
        = comment.name
        = ": "
        = comment.memo
        = " "
        = link_to t(:Edit), edit_book_comment_path(commentable, comment)
        = " "
        = link_to t(:Destroy), [commentable, comment], method: :delete, data: { confirm: t(:Are_you_sure) }
br
= paginate @comments
= form_for([commentable, commentable.comments.build]) do |f|
  p
    = "#{Comment.human_attribute_name("name")}: "
    = f.text_field :name
  p
    = "#{Comment.human_attribute_name("memo")}: "
    = f.text_field :memo
  p
    = f.submit

app/views/comments/new.html.slim
h1
  = t(:New_Model, {model: Comment.model_name.human})
= render 'form', comment: @comment
= link_to t(:Back), comments_path

app/views/comments/show.html.slim
p
  strong
    = @comment.model_name.human
p
  strong
    = "#{Comment.human_attribute_name("name")}: "
  = @comment.name
p
  strong
    = "#{Comment.human_attribute_name("memo")}: "
  = @comment.memo
= link_to t(:Back), @commentable