config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: redirect("/books")

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",

    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :follows, only: [:create, :destroy]
  resources :followings, only: [:show]
  resources :followers, only: [:show]
  resources :users

  resources :books do
    resources :comments
  end

  resources :reports do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  has_many :comments, as: :commentable
  paginates_per 5
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.page(params[:page])
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: I18n.t(:Model_was_successfully_created, model: Report.model_name.human) }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: I18n.t(:Model_was_successfully_updated, model: Report.model_name.human) }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: I18n.t(:Model_was_successfully_destroyed, model: Report.model_name.human) }
      format.json { head :no_content }
    end
  end

  private
    def set_report
      @report = Report.find(params[:id])
    end

    def report_params
      params.require(:report).permit(:title, :emotion, :body, :author, :datetime)
    end
end

app/views/reports/_form.html.slim
= form_with(model: report, local: true) do |form|
  - if report.errors.any?
    #error_explanation
      h2
        = pluralize(report.errors.count, t(:error))
        = t(:prohibited_this_model_from_being_saved, model: Report.model_name.human)
      ul
        - report.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :emotion
    = form.text_field :emotion
  .field
    = form.label :body
    = form.text_area :body
  .field
    = form.label :author
    = form.text_field :author
  .field
    = form.label :datetime
    = form.datetime_select :datetime
  .actions
    = form.submit

app/views/reports/edit.html.slim
h1
  = t(:Editing_Model, model: Report.model_name.human)
= render 'form', report: @report
= link_to t(:Show), @report
|  | 
= link_to t(:Back), reports_path

app/views/reports/index.html.slim
h1
  = "#{Report.model_name.human}"
table
  thead
    tr
      th
        = Report.human_attribute_name("title")
      th
        = Report.human_attribute_name("emotion")
      th
        = Report.human_attribute_name("body")
      th
        = Report.human_attribute_name("author")
      th
        = Report.human_attribute_name("datetime")
      th[colspan="3"]
  tbody
    - @reports.each do |report|
      tr
        td
          = report.title
        td
          = report.emotion
        td
          = report.body
        td
          = report.author
        td
          = l(report.datetime, format: :long)
        td
          = link_to t(:Show), report
        td
          = link_to t(:Edit), edit_report_path(report)
        td
          = link_to t(:Destroy), report, method: :delete, data: { confirm: t(:Are_you_sure) }
br
= paginate @reports
= link_to t(:New_Model, model: @reports.model_name.human), new_report_path

app/views/reports/new.html.slim
h1
  = t(:New_Model, model: @report.model_name.human)
= render 'form', report: @report
= link_to t(:Back), reports_path

app/views/reports/show.html.slim
p
  strong
    = "#{Report.human_attribute_name("title")}: "
  = @report.title
p
  strong
    = "#{Report.human_attribute_name("emotion")}: "
  = @report.emotion
p
  strong
    = "#{Report.human_attribute_name("body")}: "
  = @report.body
p
  strong
    = "#{Report.human_attribute_name("author")}: "
  = @report.author
p
  strong
    = "#{Report.human_attribute_name("datetime")}: "
  = l(@report.datetime, format: :long)
- commentable = @report
= render template: "comments/index", locals: { commentable: @report }
= link_to t(:Edit), edit_report_path(@report)
|  | 
= link_to t(:Back), reports_path